### ISSUE TITLE
Implement Authentication

### ISSUE THREAD

**Issue by quigongian** [quigongian/ArthasAI#10]

**Comment by VincentCarrancho** [comment]
Implemented authentication. @quigongian please create a supabase instance and DM me 2 things: supabase project URL and supabase anon key.

**Comment by VincentCarrancho** [comment]
@quigongian @Jose-Codes finished implementing an auth service to our app. We should discus any routes that needs protection.

**Comment by quigongian** [comment]
![image](https://github.com/arthasai/ArthasAI/assets/74694864/5330f776-dca7-4f92-98d8-823a37b0408c)

Hey it looks like this implementation isn't deploying.  

Error: Your project's URL and Key are required to create a Supabase client!

Are there env keys that needed be added to the deployment service? If so please send them to me so that I can put this in the next deployment settings.
